@extends('layouts.app')
@section('content')
<h1>{{ __('messages.dashboard') }}</h1>
<div class="grid-cards">
@foreach($organisations as $organisation)<article class="card"><h2>{{ $organisation->name }}</h2><div class="actions">@if(auth()->user()->hasOrganisationPermission($organisation->id,'forms.view'))<a class="btn" href="{{ route('forms.index',$organisation) }}">{{ __('messages.forms') }}</a>@endif @if(auth()->user()->hasOrganisationPermission($organisation->id,'submissions.view'))<a class="btn" href="{{ route('admin.submissions.index',$organisation) }}">{{ __('messages.submissions') }}</a>@endif @if(auth()->user()->hasOrganisationPermission($organisation->id,'exports.create'))<a class="btn" href="{{ route('exports.index',$organisation) }}">{{ __('messages.exports') }}</a>@endif @if(auth()->user()->hasOrganisationPermission($organisation->id,'users.manage'))<a class="btn" href="{{ route('users.index',$organisation) }}">{{ __('messages.users') }}</a>@endif @if(auth()->user()->hasOrganisationPermission($organisation->id,'audit.view'))<a class="btn" href="{{ route('audit.index',$organisation) }}">{{ __('messages.audit') }}</a>@endif</div></article>@endforeach
</div>
<section class="mt-8"><h2>{{ __('messages.available_forms') }}</h2><div class="grid-cards">@forelse($available as $publication)<article class="card"><h3>{{ $publication->formVersion->localizedTitle() }}</h3><p>{{ $publication->name }}</p><a class="btn primary" href="{{ route('publications.show',$publication) }}">{{ __('messages.open_form') }}</a></article>@empty<p>{{ __('messages.no_records') }}</p>@endforelse</div></section>
<section class="mt-8"><h2>{{ __('messages.active_attempts') }}</h2>@forelse($activeSubmissions as $submission)<a class="list-row" href="{{ route('submissions.take',$submission) }}">{{ $submission->formVersion->localizedTitle() }} · {{ __('messages.continue') }}</a>@empty<p>{{ __('messages.no_records') }}</p>@endforelse</section>
<section class="mt-8"><h2>{{ __('messages.completed_submissions') }}</h2>@forelse($completed as $submission)<a class="list-row" href="{{ route('submissions.complete',$submission) }}">{{ $submission->formVersion->localizedTitle() }} · {{ $submission->status }}</a>@empty<p>{{ __('messages.no_records') }}</p>@endforelse</section>
@endsection
