@extends('layouts.app')
@section('title', __('messages.manage_questionnaires'))
@section('content')
<div class="page-header"><div><h1>{{ __('messages.manage_questionnaires') }}</h1><p>{{ $patientCase->first_name }} {{ $patientCase->last_name }} · {{ __('messages.patient_id') }}: {{ $patientCase->external_patient_code ?: '—' }} · {{ __('messages.slot_number') }} {{ $patientCase->slot_number }}</p></div><a class="btn" href="{{ route('doctor.dashboard', ['organisation_id'=>$patientCase->organisation_id, 'doctor_id'=>$patientCase->doctor_id]) }}">{{ __('messages.back') }}</a></div>
@if(session('patient_access_url'))<div class="notice success"><strong>{{ __('messages.patient_link_copy_once') }}</strong><div class="actions mt-3"><input id="patient-access-url" readonly value="{{ session('patient_access_url') }}"><button type="button" class="btn primary" data-copy-target="patient-access-url">{{ __('messages.copy_link') }}</button></div></div>@endif
<div class="grid-cards mb-6">
<section class="card"><h2>{{ __('messages.assign_questionnaire') }}</h2>
@if($publications->isEmpty())<p>{{ __('messages.no_available_questionnaires') }}</p>@else<form method="POST" action="{{ route('doctor.questionnaires.store',$patientCase) }}" class="stack">@csrf
<label>{{ __('messages.publication') }}<select name="publication_id" required>@foreach($publications as $publication)<option value="{{ $publication->id }}">{{ $publication->name }} · {{ $publication->formVersion->localizedTitle() }}</option>@endforeach</select></label>
<label>{{ __('messages.label') }}<input name="label" required maxlength="255"></label><label>{{ __('messages.order') }}<input type="number" name="display_order" min="1" max="1000" value="{{ ($patientCase->assignments->max('display_order') ?? 0)+1 }}" required></label><button class="btn primary">{{ __('messages.assign') }}</button></form>@endif</section>
<section class="card"><h2>{{ __('messages.secure_patient_link') }}</h2>
@if($activePackage)<p>{{ __('messages.link_active_until', ['date'=>$activePackage->expires_at->format('Y-m-d H:i')]) }}</p><form method="POST" action="{{ route('doctor.patient-link.revoke',[$patientCase,$activePackage]) }}" data-confirm="{{ __('messages.confirm_revoke_link') }}">@csrf @method('DELETE')<button class="btn danger">{{ __('messages.revoke_link') }}</button></form>@else<p>{{ __('messages.no_active_patient_link') }}</p>@endif
<form method="POST" action="{{ route('doctor.patient-link.issue',$patientCase) }}" class="stack mt-4">@csrf<label>{{ __('messages.link_validity') }}<select name="expires_in_days">@foreach([7,14,30,60,90] as $days)<option value="{{ $days }}" @selected($days===30)>{{ trans_choice('messages.days_count',$days,['count'=>$days]) }}</option>@endforeach</select></label><button class="btn primary">{{ $activePackage ? __('messages.regenerate_link') : __('messages.create_link') }}</button></form></section>
</div>
<section class="card"><h2>{{ __('messages.assigned_questionnaires') }}</h2><div class="table-wrap"><table><thead><tr><th>{{ __('messages.order') }}</th><th>{{ __('messages.label') }}</th><th>{{ __('messages.status') }}</th></tr></thead><tbody>@forelse($patientCase->assignments as $assignment)<tr><td>{{ $assignment->display_order }}</td><td>{{ $assignment->label }}</td><td>{{ __('messages.'.$assignment->status()) }}</td></tr>@empty<tr><td colspan="3">{{ __('messages.no_records') }}</td></tr>@endforelse</tbody></table></div></section>
@endsection
