<?php
$lv = require __DIR__.'/../lv/messages.php';
return array_replace($lv, [
 'create_platform_admin'=>'Создать администратора платформы','promote_platform_admin'=>'Назначить администратором платформы','confirm_platform_admin_promotion'=>'Назначить этого пользователя администратором платформы?','platform_admin_created'=>'Администратор платформы создан.','platform_admin_promoted'=>'Пользователь назначен администратором платформы.','already_platform_admin'=>'Пользователь уже является администратором платформы.',
 'invalid_scoring_rule'=>'Правило оценивания ссылается на недопустимый правильный ответ.','correct_answer_after_options'=>'Сохраните компонент, затем выберите правильные ответы из сохранённых вариантов.','conditional_visibility'=>'Условная видимость','source'=>'Источник','operator'=>'Оператор','value'=>'Значение','target_component'=>'Целевой компонент','target_section'=>'Целевой раздел','tolerance'=>'Допуск','membership_email_help'=>'Введите точный адрес известного пользователя; каталог пользователей платформы не раскрывается.','membership_candidate_not_found'=>'Активный пользователь с таким адресом недоступен.','contradictory_identity_settings'=>'Нельзя одновременно разрешить анонимные и требовать идентифицированные ответы.','archived_form_cannot_publish'=>'Нельзя активировать публикацию архивной формы.',
 'invalid_scoring_rule'=>'Правило оценивания ссылается на недопустимый правильный ответ.',
 'attachments'=>'Вложения','attachment'=>'Вложение','upload'=>'Загрузить','invalid_attachment'=>'Недопустимое вложение.','system_users'=>'Пользователи системы','roles_permissions'=>'Роли и разрешения','disable'=>'Отключить','enable'=>'Включить','cannot_disable_self'=>'Нельзя отключить собственную учётную запись.','submission_notification_subject'=>'Получен ответ на форму','submission_notification_line'=>'Завершён новый ответ на форму «:form».',
 'app_name'=>'Универсальный конструктор форм','dashboard'=>'Главная','login'=>'Войти','logout'=>'Выйти','register'=>'Регистрация','email'=>'Эл. почта','password'=>'Пароль','password_confirmation'=>'Повторите пароль','name'=>'Имя','student_id'=>'ID участника','save'=>'Сохранить','saved'=>'Сохранено.','delete'=>'Удалить','edit'=>'Изменить','create'=>'Создать','back'=>'Назад','status'=>'Статус','actions'=>'Действия','yes'=>'Да','no'=>'Нет','language'=>'Язык','organisations'=>'Организации','organisation'=>'Организация','users'=>'Пользователи','forms'=>'Формы','new_form'=>'Новая форма','form_name'=>'Название формы','preset'=>'Шаблон','blank'=>'Пустая форма','test'=>'Тест / экзамен','patient_questionnaire'=>'Анкета пациента','builder'=>'Конструктор','preview'=>'Предпросмотр','publish'=>'Опубликовать','new_draft'=>'Новый черновик','duplicate'=>'Дублировать','archive'=>'Архивировать','sections'=>'Разделы','section'=>'Раздел','first_section'=>'Раздел 1','add_section'=>'Добавить раздел','add_component'=>'Добавить компонент','component_type'=>'Тип компонента','label'=>'Название','description'=>'Описание','help_text'=>'Подсказка','required'=>'Обязательно','visible'=>'Видимый','options'=>'Варианты ответа','settings'=>'Настройки','max_points'=>'Максимум баллов','manual_grading'=>'Ручная оценка','publications'=>'Публикации','create_publication'=>'Создать публикацию','active'=>'Активна','inactive'=>'Неактивна','access_mode'=>'Режим доступа','authenticated'=>'Авторизованные пользователи','public_link'=>'Публичная ссылка','access_code'=>'Код доступа','invitation'=>'Индивидуальное приглашение','attempt_limit'=>'Лимит попыток','timer'=>'Таймер','duration_minutes'=>'Длительность в минутах','result_visibility'=>'Видимость результата','consent_required'=>'Требуется согласие','autosave'=>'Автосохранение','resume'=>'Продолжение','start'=>'Начать','available_forms'=>'Доступные формы','active_attempts'=>'Активные попытки','completed_submissions'=>'Завершённые ответы','continue'=>'Продолжить','progress'=>'Прогресс','previous'=>'Назад','next'=>'Далее','submit'=>'Отправить','time_remaining'=>'Осталось времени','saving'=>'Сохранение…','saved_state'=>'Сохранено','offline'=>'Нет сети','save_error'=>'Ошибка сохранения','submission_complete'=>'Ответ отправлен.','submissions'=>'Ответы','respondent'=>'Респондент','answer'=>'Ответ','points'=>'Баллы','grading'=>'Оценивание','exports'=>'Экспорт','download'=>'Скачать','audit'=>'Журнал аудита','roles'=>'Роли','security_warning'=>'Этот MVP не сертифицирован для реальных медицинских данных. Перед таким использованием необходима независимая оценка безопасности и конфиденциальности.','no_records'=>'Нет записей.','confirm_delete'=>'Удалить этот элемент черновика?','validation_errors'=>'Исправьте ошибки.','yes'=>'Да','no'=>'Нет'
]);
