<?php

namespace App\Http\Controllers;

use App\Domain\Forms\BuilderService;
use App\Domain\Forms\ComponentRegistry;
use App\Domain\Forms\FormAuthoringService;
use App\Http\Requests\StoreComponentRequest;
use App\Http\Requests\StoreSectionRequest;
use App\Models\Form;
use App\Models\FormComponent;
use App\Models\FormSection;
use App\Models\ConditionalRule;
use Illuminate\Http\Request;

class BuilderController extends Controller
{
    public function edit(Form $form, ComponentRegistry $registry) { $this->authorize('update',$form); $version=$form->versions()->where('status','draft')->latest('version_number')->with('sections.components.options','sections.components.scoringRule','conditionalRules.actions','attachments')->first(); return view('forms.builder',compact('form','version')+['registry'=>$registry->all()]); }
    public function preview(Form $form) { $this->authorize('view',$form); $version=$form->versions()->where('status','draft')->latest('version_number')->with('sections.components.options')->firstOrFail(); return view('forms.preview',compact('form','version')); }
    public function addSection(StoreSectionRequest $request, Form $form, FormAuthoringService $service) { $version=$form->versions()->where('status','draft')->latest('version_number')->firstOrFail(); $service->addSection($version,$request->title); return back()->with('success',__('messages.saved')); }
    public function updateSection(Request $request, Form $form, FormSection $section, BuilderService $service) { $this->authorize('update',$form); abort_unless($section->formVersion->form_id===$form->id,404); $service->updateSection($section,$request->validate(['title'=>'required|string|max:255','description'=>'nullable|string|max:5000','visible'=>'sometimes|boolean','translations'=>'nullable|array'])); return back()->with('success',__('messages.saved')); }
    public function moveSection(Request $request, Form $form, FormSection $section, BuilderService $service) { $this->authorize('update',$form); abort_unless($section->formVersion->form_id===$form->id,404); $service->moveSection($section,$request->validate(['direction'=>'required|in:up,down'])['direction']); return back(); }
    public function deleteSection(Form $form, FormSection $section, BuilderService $service) { $this->authorize('update',$form); abort_unless($section->formVersion->form_id===$form->id,404); $service->deleteSection($section); return back()->with('success',__('messages.deleted')); }
    public function addComponent(StoreComponentRequest $request, Form $form, FormAuthoringService $service) { $version=$form->versions()->where('status','draft')->latest('version_number')->firstOrFail(); $section=FormSection::findOrFail($request->section_id); $service->addComponent($version,$section,$request->validated()); return back()->with('success',__('messages.saved')); }
    public function updateComponent(Request $request, Form $form, FormComponent $component, BuilderService $service) { $this->authorize('update',$form); abort_unless($component->formVersion->form_id===$form->id,404); $data=$request->validate(['label'=>'required|string|max:500','description'=>'nullable|string|max:10000','help_text'=>'nullable|string|max:2000','is_required'=>'sometimes|boolean','visible'=>'sometimes|boolean','max_points'=>'nullable|numeric|min:0','manual_grading'=>'sometimes|boolean','settings'=>'nullable|array','translations'=>'nullable|array','options'=>'nullable|array','options.existing'=>'nullable|array','options.existing.*'=>'nullable|string|max:500','options.new'=>'nullable|array','options.new.*'=>'nullable|string|max:500','scoring_strategy'=>'nullable|in:none,single_choice,multiple_all_or_nothing,multiple_partial,yes_no,numeric_exact,numeric_tolerance,manual','scoring_rules'=>'nullable|array']); $component->load('scoringRule');$service->updateComponent($component,$data); return back()->with('success',__('messages.saved')); }
    public function copyComponent(Form $form, FormComponent $component, BuilderService $service) { $this->authorize('update',$form); abort_unless($component->formVersion->form_id===$form->id,404); $component->load('options','validationRules','scoringRule','section'); $service->copyComponent($component); return back()->with('success',__('messages.duplicated')); }
    public function moveComponent(Request $request, Form $form, FormComponent $component, BuilderService $service) { $this->authorize('update',$form); abort_unless($component->formVersion->form_id===$form->id,404); $data=$request->validate(['direction'=>'required|in:up,down,section','section_id'=>'nullable|integer|exists:form_sections,id']); $service->moveComponent($component,$data['section_id']??null ? FormSection::find($data['section_id']) : null,$data['direction']); return back(); }
    public function deleteComponent(Form $form, FormComponent $component) { $this->authorize('update',$form); abort_unless($component->formVersion->form_id===$form->id,404); $component->load('options','validationRules','scoringRule'); \DB::transaction(function()use($component){$component->scoringRule?->delete();$component->validationRules()->delete();$component->options()->delete();$component->delete();}); return back()->with('success',__('messages.deleted')); }
    public function addCondition(Request $request, Form $form) { $this->authorize('update',$form);$version=$form->versions()->where('status','draft')->latest('version_number')->firstOrFail();$data=$request->validate(['source_component_id'=>'required|integer','operator'=>'required|in:equals,not_equals,contains,greater_than,less_than,is_answered,is_not_answered','comparison_value'=>'nullable','action'=>'required|in:show_component,hide_component,show_section,hide_section','target_component_id'=>'nullable|integer','target_section_id'=>'nullable|integer']);abort_if((int)($data['target_component_id']??0)===(int)$data['source_component_id'],422);abort_unless($version->components()->whereKey($data['source_component_id'])->exists(),422);if(!empty($data['target_component_id']))abort_unless($version->components()->whereKey($data['target_component_id'])->exists(),422);if(!empty($data['target_section_id']))abort_unless($version->sections()->whereKey($data['target_section_id'])->exists(),422);\DB::transaction(function()use($version,$data){$rule=$version->conditionalRules()->create(['source_component_id'=>$data['source_component_id'],'operator'=>$data['operator'],'comparison_value'=>['value'=>$data['comparison_value']??null],'priority'=>((int)$version->conditionalRules()->max('priority'))+1]);$rule->actions()->create(['action'=>$data['action'],'target_component_id'=>$data['target_component_id']??null,'target_section_id'=>$data['target_section_id']??null]);});return back()->with('success',__('messages.saved'));}
    public function deleteCondition(Form $form, ConditionalRule $condition) { $this->authorize('update',$form);abort_unless($condition->formVersion->form_id===$form->id,404);\DB::transaction(function()use($condition){$condition->actions()->delete();$condition->delete();});return back()->with('success',__('messages.deleted'));}
}
