@extends('layouts.app')
@section('content')
@php($showFallbackIndicators=true)
@php($contentLocale=$locale)
<div class="page-header"><div><h1>{{ $version->localizedTitle($contentLocale) }} · {{ __('messages.preview') }}</h1>@if($version->localizedDescription($contentLocale))<p class="multiline-text" style="white-space:pre-wrap">{{ $version->localizedDescription($contentLocale) }}</p>@endif</div><a class="btn" href="{{ route('forms.builder',$form) }}">{{ __('messages.builder') }}</a></div>
<nav class="preview-locales" aria-label="{{ __('messages.preview_language') }}">@foreach(config('form_locales.supported') as $code)<a class="btn {{ $contentLocale===$code?'primary':'' }}" href="{{ route('forms.preview',$form) }}?locale={{ $code }}">{{ strtoupper($code) }}</a>@endforeach</nav>
@if($version->usesContentFallback($contentLocale))<p class="fallback-indicator">{{ __('messages.fallback_used') }}</p>@endif
<div class="renderer preview">@foreach($version->sections as $section)<section class="form-page" @if(!$section->visible)hidden @endif><h2>{{ $section->localizedTitle($contentLocale) }}</h2>@if($section->localizedDescription($contentLocale))<p class="multiline-text" style="white-space:pre-wrap">{{ $section->localizedDescription($contentLocale) }}</p>@endif @if($showFallbackIndicators&&$section->usesContentFallback($contentLocale))<span class="fallback-indicator">{{ __('messages.fallback_used') }}</span>@endif @foreach($section->components as $component)@include('forms.components.generic',['answers'=>[]])@endforeach</section>@endforeach</div>
@if($version->localizedCompletionText($contentLocale) || $version->localizedResultText($contentLocale))<section class="card renderer mt-6"><h2>{{ __('messages.completion_and_result_content') }}</h2>@if($version->localizedCompletionText($contentLocale))<p class="multiline-text" style="white-space:pre-wrap">{{ $version->localizedCompletionText($contentLocale) }}</p>@endif @if($version->localizedResultText($contentLocale))<p class="multiline-text" style="white-space:pre-wrap">{{ $version->localizedResultText($contentLocale) }}</p>@endif</section>@endif
@endsection
